package com.koriebruh.paymentgatewaycip.mock;

import java.math.BigDecimal;

/**
 * Contract for Biller Aggregator payment operations.
 *
 * <p>Simulates the biller-side payment forwarding.  A mock implementation
 * ({@link BillerClientMock}) handles all local and test traffic while a
 * real HTTP adapter would be used in production.
 */
public interface BillerClient {

    /**
     * Forward a payment to the biller aggregator.
     *
     * @param orderId       correlation key for the payment
     * @param amount        payment amount
     * @param paymentMethod e.g. {@code VIRTUAL_ACCOUNT}, {@code QRIS}
     * @return a {@link BillerResponse} containing the biller reference
     */
    BillerResponse pay(String orderId, BigDecimal amount, String paymentMethod);

    // -----------------------------------------------------------------------
    //  Value object returned by the biller system
    // -----------------------------------------------------------------------

    /**
     * Immutable response from the Biller pay call.
     *
     * @param success         {@code true} if the payment was accepted
     * @param billerReference unique reference generated by the biller
     * @param failureReason   human-readable reason when {@code success == false}
     */
    record BillerResponse(
            boolean success,
            String  billerReference,
            String  failureReason
    ) {}
}
