package com.koriebruh.paymentgatewaycip.mock;

import java.math.BigDecimal;

/**
 * Contract for Core Banking debit operations.
 *
 * <p>In production this would be a Feign/RestClient talking to the actual
 * core-banking system.  During local development and tests a mock
 * implementation ({@link CoreBankingClientMock}) is active instead.
 */
public interface CoreBankingClient {

    /**
     * Debit {@code amount} from {@code accountNumber}.
     *
     * @param accountNumber the account to debit
     * @param amount        the amount to debit (must be positive)
     * @param orderId       correlation key for idempotency
     * @return a {@link CoreBankingResponse} containing the bank reference
     * and whether the debit succeeded
     */
    CoreBankingResponse debit(String accountNumber, BigDecimal amount, String orderId);

    // -----------------------------------------------------------------------
    //  Value object returned by the core-banking system
    // -----------------------------------------------------------------------

    /**
     * Immutable response from the Core Banking debit call.
     *
     * @param success           {@code true} if the debit was processed
     * @param corebankReference unique reference generated by the bank
     * @param failureReason     human-readable reason when {@code success == false}
     */
    record CoreBankingResponse(
            boolean success,
            String corebankReference,
            String failureReason
    ) {
    }
}
